Rename dist/ to zdist/ in blut acceptance of the reality that many views will be alphabetical by file name, and we want this at the bottom.

diff --git a/scripts/pre-commit b/scripts/pre-commit
--- a/scripts/pre-commit
+++ b/scripts/pre-commit
@@ -4,8 +4,8 @@ set -veuxo pipefail;
 npm version --no-git-tag-version prerelease;
 git add package.json;
 npm run prepublish && ( \
-  echo "exit status 0" | tee dist/0S-SUCCESS \
+  echo "exit status 0" | tee zdist/0S-SUCCESS \
 ) || ( \
-  echo "exit status $?" | tee dist/0F-FAILURE \
+  echo "exit status $?" | tee zdist/0F-FAILURE \
 );
-git add dist/;
+git add zdist/;
