Cleaning up scripts.

diff --git a/scripts/pre-commit b/scripts/pre-commit
--- a/scripts/pre-commit
+++ b/scripts/pre-commit
@@ -3,5 +3,9 @@ set -veuo pipefail;
 
 npm version --no-git-tag-version prerelease;
 git add package.json;
-npm run prepublish || (echo "$?" > dist/0X-FAILED && git diff dist/0*-*);
+npm run prepublish && ( \
+  echo "exit status 0" | tee dist/0S-SUCCESS \
+) || ( \
+  echo "exit status $?" | tee dist/0F-FAILURE \
+);
 git add dist/;
